ADVENTURE_CONFIG = {
    1: {
        "villains": ["draco", "quirrell"],
        "dark_arts_count": 1,
        "locations": ["diagon_alley", "leaky_cauldron", "hogwarts_castle"],
        "market_cards": [
            "alohomora", "incendio", "lumos", "reparo", "expelliarmus",
            "bertie_botts", "nimbus_2000", "hogwarts_founders",
        ],
        "hero_start_health": {"harry": 10, "ron": 10, "hermione": 10, "neville": 10},
        "dark_arts_cards": ["flipendo", "expulso", "chaos"],
    },
    2: {
        "villains": ["draco", "quirrell", "lucius"],
        "dark_arts_count": 2,
        "locations": ["diagon_alley", "leaky_cauldron", "chamber_of_secrets", "hogwarts_castle"],
        "market_cards": [
            "alohomora", "incendio", "lumos", "reparo", "expelliarmus",
            "bertie_botts", "nimbus_2000", "hogwarts_founders",
            "polyjuice_potion", "dobby",
        ],
        "hero_start_health": {"harry": 10, "ron": 10, "hermione": 10, "neville": 10},
        "dark_arts_cards": ["flipendo", "expulso", "chaos", "basilisk"],
    },
}

VILLAIN_DATA = {
    "draco": {
        "id": "draco",
        "name_it": "Draco Malfoy",
        "name_en": "Draco Malfoy",
        "health_max": 6,
        "attack_tokens": 1,
        "attack_each_turn": [{"type": "control_token", "target": "active_location", "value": 1}],
        "ability_text_it": "Ogni turno: aggiungi 1 token controllo al luogo attivo.",
        "ability_text_en": "Each turn: add 1 control token to the active location.",
    },
    "quirrell": {
        "id": "quirrell",
        "name_it": "Professor Quirrell",
        "name_en": "Professor Quirrell",
        "health_max": 7,
        "attack_tokens": 2,
        "attack_each_turn": [{"type": "damage", "target": "active_hero", "value": 1}],
        "ability_text_it": "Ogni turno: l'eroe attivo perde 1 salute.",
        "ability_text_en": "Each turn: the active hero loses 1 health.",
    },
    "lucius": {
        "id": "lucius",
        "name_it": "Lucius Malfoy",
        "name_en": "Lucius Malfoy",
        "health_max": 9,
        "attack_tokens": 2,
        "attack_each_turn": [
            {"type": "control_token", "target": "active_location", "value": 1},
            {"type": "damage", "target": "all_heroes", "value": 1},
        ],
        "ability_text_it": "Ogni turno: aggiungi 1 token controllo e infliggi 1 danno a tutti.",
        "ability_text_en": "Each turn: add 1 control token and deal 1 damage to all heroes.",
    },
    "bellatrix": {
        "id": "bellatrix",
        "name_it": "Bellatrix Lestrange",
        "name_en": "Bellatrix Lestrange",
        "health_max": 9,
        "attack_tokens": 2,
        "attack_each_turn": [{"type": "damage", "target": "all_heroes", "value": 2}],
        "ability_text_it": "Ogni turno: tutti gli eroi perdono 2 salute.",
        "ability_text_en": "Each turn: all heroes lose 2 health.",
    },
    "fenrir": {
        "id": "fenrir",
        "name_it": "Fenrir Grayback",
        "name_en": "Fenrir Greyback",
        "health_max": 8,
        "attack_tokens": 2,
        "attack_each_turn": [{"type": "damage", "target": "random_hero", "value": 3}],
        "ability_text_it": "Ogni turno: un eroe casuale perde 3 salute.",
        "ability_text_en": "Each turn: a random hero loses 3 health.",
    },
    "dolohov": {
        "id": "dolohov",
        "name_it": "Antonin Dolohov",
        "name_en": "Antonin Dolohov",
        "health_max": 7,
        "attack_tokens": 1,
        "attack_each_turn": [{"type": "discard", "target": "active_hero", "value": 1}],
        "ability_text_it": "Ogni turno: l'eroe attivo scarta 1 carta.",
        "ability_text_en": "Each turn: the active hero discards 1 card.",
    },
    "voldemort_a4": {
        "id": "voldemort_a4",
        "name_it": "Voldemort",
        "name_en": "Voldemort",
        "health_max": 12,
        "attack_tokens": 3,
        "attack_each_turn": [
            {"type": "damage", "target": "all_heroes", "value": 1},
            {"type": "control_token", "target": "active_location", "value": 1},
        ],
        "ability_text_it": "Ogni turno: 1 danno a tutti + 1 token controllo.",
        "ability_text_en": "Each turn: 1 damage to all + 1 control token.",
    },
    "umbridge": {
        "id": "umbridge",
        "name_it": "Dolores Umbridge",
        "name_en": "Dolores Umbridge",
        "health_max": 8,
        "attack_tokens": 2,
        "attack_each_turn": [{"type": "detain", "target": "active_hero", "value": 1}],
        "ability_text_it": "Ogni turno: l'eroe attivo non può comprare carte questo turno.",
        "ability_text_en": "Each turn: the active hero cannot buy cards this turn.",
    },
    "nagini": {
        "id": "nagini",
        "name_it": "Nagini",
        "name_en": "Nagini",
        "health_max": 6,
        "attack_tokens": 1,
        "attack_each_turn": [{"type": "damage", "target": "active_hero", "value": 2}],
        "ability_text_it": "Ogni turno: l'eroe attivo perde 2 salute.",
        "ability_text_en": "Each turn: the active hero loses 2 health.",
    },
    "voldemort_final": {
        "id": "voldemort_final",
        "name_it": "Lord Voldemort",
        "name_en": "Lord Voldemort",
        "health_max": 15,
        "attack_tokens": 3,
        "attack_each_turn": [
            {"type": "damage", "target": "all_heroes", "value": 2},
            {"type": "control_token", "target": "active_location", "value": 2},
        ],
        "ability_text_it": "Ogni turno: 2 danni a tutti + 2 token controllo.",
        "ability_text_en": "Each turn: 2 damage to all + 2 control tokens.",
    },
}

LOCATION_DATA = {
    "diagon_alley": {
        "id": "diagon_alley",
        "name_it": "Diagon Alley",
        "name_en": "Diagon Alley",
        "control_max": 3,
        "penalty_text_it": "I malvagi aggiungono 1 token controllo quando attaccano.",
        "penalty_text_en": "Villains add 1 control token when attacking.",
    },
    "leaky_cauldron": {
        "id": "leaky_cauldron",
        "name_it": "Il Calderone Magico",
        "name_en": "The Leaky Cauldron",
        "control_max": 3,
        "penalty_text_it": "Ogni eroe perde 1 salute all'inizio del turno.",
        "penalty_text_en": "Each hero loses 1 health at the start of the turn.",
    },
    "hogwarts_castle": {
        "id": "hogwarts_castle",
        "name_it": "Castello di Hogwarts",
        "name_en": "Hogwarts Castle",
        "control_max": 4,
        "penalty_text_it": "Se Hogwarts cade, i giocatori perdono.",
        "penalty_text_en": "If Hogwarts falls, players lose.",
    },
    "chamber_of_secrets": {
        "id": "chamber_of_secrets",
        "name_it": "Camera dei Segreti",
        "name_en": "Chamber of Secrets",
        "control_max": 4,
        "penalty_text_it": "Ogni token controllo riduce di 1 il valore delle carte comprate.",
        "penalty_text_en": "Each control token reduces bought card value by 1.",
    },
}

CARD_DATA = {
    "alohomora": {
        "id": "alohomora",
        "type": "hogwarts",
        "adventure": 1,
        "name_it": "Alohomora",
        "name_en": "Alohomora",
        "cost": 0,
        "effects": [{"type": "influence", "value": 1}],
        "ability_text_it": "Guadagna 1 🔮.",
        "ability_text_en": "Gain 1 🔮.",
    },
    "incendio": {
        "id": "incendio",
        "type": "hogwarts",
        "adventure": 1,
        "name_it": "Incendio",
        "name_en": "Incendio",
        "cost": 4,
        "effects": [{"type": "attack", "value": 2}],
        "ability_text_it": "Guadagna 2 ⚔️.",
        "ability_text_en": "Gain 2 ⚔️.",
    },
    "lumos": {
        "id": "lumos",
        "type": "hogwarts",
        "adventure": 1,
        "name_it": "Lumos",
        "name_en": "Lumos",
        "cost": 4,
        "effects": [{"type": "draw", "value": 2}],
        "ability_text_it": "Pesca 2 carte.",
        "ability_text_en": "Draw 2 cards.",
    },
    "reparo": {
        "id": "reparo",
        "type": "hogwarts",
        "adventure": 1,
        "name_it": "Reparo",
        "name_en": "Reparo",
        "cost": 3,
        "effects": [{"type": "heal", "value": 2}],
        "ability_text_it": "Cura 2 salute a qualsiasi eroe.",
        "ability_text_en": "Heal 2 health to any hero.",
    },
    "expelliarmus": {
        "id": "expelliarmus",
        "type": "hogwarts",
        "adventure": 1,
        "name_it": "Expelliarmus",
        "name_en": "Expelliarmus",
        "cost": 5,
        "effects": [{"type": "attack", "value": 1}, {"type": "draw", "value": 1}],
        "ability_text_it": "Guadagna 1 ⚔️ e pesca 1 carta.",
        "ability_text_en": "Gain 1 ⚔️ and draw 1 card.",
    },
    "bertie_botts": {
        "id": "bertie_botts",
        "type": "hogwarts",
        "adventure": 1,
        "name_it": "Bertie Bott's Beans",
        "name_en": "Bertie Bott's Beans",
        "cost": 2,
        "effects": [{"type": "influence", "value": 2}],
        "ability_text_it": "Guadagna 2 🔮.",
        "ability_text_en": "Gain 2 🔮.",
    },
    "nimbus_2000": {
        "id": "nimbus_2000",
        "type": "hogwarts",
        "adventure": 1,
        "name_it": "Nimbus 2000",
        "name_en": "Nimbus 2000",
        "cost": 6,
        "effects": [{"type": "attack", "value": 1}, {"type": "influence", "value": 1}, {"type": "draw", "value": 1}],
        "ability_text_it": "Guadagna 1 ⚔️, 1 🔮 e pesca 1 carta.",
        "ability_text_en": "Gain 1 ⚔️, 1 🔮, and draw 1 card.",
    },
    "flipendo": {
        "id": "flipendo",
        "type": "dark_arts",
        "adventure": 1,
        "name_it": "Flipendo",
        "name_en": "Flipendo",
        "cost": 0,
        "effects": [{"type": "damage_all", "value": 1}],
        "ability_text_it": "Ogni eroe perde 1 salute.",
        "ability_text_en": "Each hero loses 1 health.",
    },
    "expulso": {
        "id": "expulso",
        "type": "dark_arts",
        "adventure": 1,
        "name_it": "Expulso",
        "name_en": "Expulso",
        "cost": 0,
        "effects": [{"type": "control_token", "value": 1}],
        "ability_text_it": "Aggiungi 1 token controllo al luogo attivo.",
        "ability_text_en": "Add 1 control token to the active location.",
    },
    "wingardium_leviosa": {
        "id": "wingardium_leviosa",
        "type": "hogwarts",
        "adventure": 1,
        "name_it": "Wingardium Leviosa",
        "name_en": "Wingardium Leviosa",
        "cost": 0,
        "effects": [{"type": "influence", "value": 1}],
        "ability_text_it": "Guadagna 1 🔮.",
        "ability_text_en": "Gain 1 🔮.",
    },
    "hogwarts_founders": {
        "id": "hogwarts_founders",
        "type": "hogwarts",
        "adventure": 1,
        "name_it": "Fondatori di Hogwarts",
        "name_en": "Hogwarts Founders",
        "cost": 6,
        "effects": [{"type": "influence", "value": 4}],
        "ability_text_it": "Guadagna 4 🔮.",
        "ability_text_en": "Gain 4 🔮.",
    },
    "polyjuice_potion": {
        "id": "polyjuice_potion",
        "type": "hogwarts",
        "adventure": 1,
        "name_it": "Pozione Polisucco",
        "name_en": "Polyjuice Potion",
        "cost": 4,
        "effects": [{"type": "draw", "value": 2}],
        "ability_text_it": "Pesca 2 carte.",
        "ability_text_en": "Draw 2 cards.",
    },
    "dobby": {
        "id": "dobby",
        "type": "hogwarts",
        "adventure": 1,
        "name_it": "Dobby",
        "name_en": "Dobby",
        "cost": 4,
        "effects": [{"type": "heal_any", "value": 2}],
        "ability_text_it": "Cura 2 salute a qualsiasi eroe.",
        "ability_text_en": "Heal 2 health to any hero.",
    },
    "chaos": {
        "id": "chaos",
        "type": "dark_arts",
        "adventure": 1,
        "name_it": "Caos",
        "name_en": "Chaos",
        "cost": 0,
        "effects": [{"type": "control_token", "value": 1}],
        "ability_text_it": "Aggiungi 1 token controllo al luogo attivo.",
        "ability_text_en": "Add 1 control token to the active location.",
    },
    "basilisk": {
        "id": "basilisk",
        "type": "dark_arts",
        "adventure": 1,
        "name_it": "Basilisco",
        "name_en": "Basilisk",
        "cost": 0,
        "effects": [{"type": "damage_active_hero", "value": 2}],
        "ability_text_it": "L'eroe attivo perde 2 salute.",
        "ability_text_en": "The active hero loses 2 health.",
    },
}
